import InvoiceItemclass
itemID=str(input("item"))
itemQTY=str(input("QTY"))

my_invoice=InvoiceItemclass.InvoiceItem(itemID,"human",itemQTY,"1000")
my_invoice.toString()
y=my_invoice.getTotal()
print(y)
x=int(input('new qty'))
my_invoice.setQty(x)
my_invoice.toString()
b=my_invoice.getTotal()
print(b)
h=my_invoice.getID()
z=my_invoice.getDesc()
u=my_invoice.getQty()
t=my_invoice.getunitprice()
print(h)
print(z)
print(u)
print(t)
